"""add collection audit and station identity

Revision ID: f233d458f264
Revises: f6d78960c08c
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "f233d458f264"
down_revision: str | None = "f6d78960c08c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "collection_runs",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("manifest", sa.JSON(), nullable=False),
        sa.Column("last_error", sa.String(length=500), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_collection_runs")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "collection_pages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.String(length=32), nullable=False),
        sa.Column("city_code", sa.String(length=6), nullable=False),
        sa.Column("adcode", sa.String(length=6), nullable=False),
        sa.Column("page", sa.Integer(), nullable=False),
        sa.Column("collected_at", sa.DateTime(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("raw_pois", sa.JSON(), nullable=False),
        sa.Column("response_hash", sa.String(length=64), nullable=False),
        sa.Column("outcomes", sa.JSON(), nullable=False),
        sa.Column("terminal", sa.Boolean(), nullable=False),
        sa.Column("capped", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["collection_runs.id"],
            name=op.f("fk_collection_pages_run_id_collection_runs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_collection_pages")),
        sa.UniqueConstraint("run_id", "adcode", "page", name=op.f("uq_collection_pages_run_id")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("ix_collection_pages_city_code"), "collection_pages", ["city_code"], unique=False
    )
    op.create_index(
        op.f("ix_collection_pages_run_id"), "collection_pages", ["run_id"], unique=False
    )
    op.add_column(
        "charging_stations", sa.Column("identity_hash", sa.String(length=64), nullable=True)
    )
    op.create_unique_constraint(
        op.f("uq_charging_stations_identity_hash"), "charging_stations", ["identity_hash"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_charging_stations_identity_hash"), "charging_stations", type_="unique"
    )
    op.drop_column("charging_stations", "identity_hash")
    # Dropping the table removes indexes; don't drop an FK-supporting index first.
    op.drop_table("collection_pages")
    op.drop_table("collection_runs")
    # ### end Alembic commands ###
