"""create foundation tables

Revision ID: f6d78960c08c
Revises:
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "f6d78960c08c"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_sources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("source_type", sa.String(length=40), nullable=False),
        sa.Column("source_url", sa.String(length=1000), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("is_demo", sa.Boolean(), server_default="0", nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_data_sources")),
        sa.UniqueConstraint("name", name=op.f("uq_data_sources_name")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "regions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("adcode", sa.String(length=6), nullable=False),
        sa.Column("level", sa.String(length=20), nullable=False),
        sa.Column("parent_adcode", sa.String(length=6), nullable=True),
        sa.Column("center_lng", sa.Numeric(precision=10, scale=7), nullable=False),
        sa.Column("center_lat", sa.Numeric(precision=10, scale=7), nullable=False),
        sa.Column("short_name", sa.String(length=40), nullable=True),
        sa.Column("group_name", sa.String(length=40), nullable=True),
        sa.Column("area_km2", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("is_demo", sa.Boolean(), server_default="0", nullable=False),
        sa.CheckConstraint(
            "area_km2 IS NULL OR area_km2 > 0", name=op.f("ck_regions_positive_area")
        ),
        sa.CheckConstraint(
            "center_lat BETWEEN -90 AND 90", name=op.f("ck_regions_center_lat_range")
        ),
        sa.CheckConstraint(
            "center_lng BETWEEN -180 AND 180", name=op.f("ck_regions_center_lng_range")
        ),
        sa.ForeignKeyConstraint(
            ["parent_adcode"], ["regions.adcode"], name=op.f("fk_regions_parent_adcode_regions")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_regions")),
        sa.UniqueConstraint("adcode", name=op.f("uq_regions_adcode")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
        mysql_engine="InnoDB",
    )
    op.create_index(op.f("ix_regions_parent_adcode"), "regions", ["parent_adcode"], unique=False)
    op.create_table(
        "charging_stations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("poi_id", sa.String(length=100), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("address", sa.String(length=500), nullable=True),
        sa.Column("province", sa.String(length=100), nullable=False),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("district", sa.String(length=100), nullable=True),
        sa.Column("adcode", sa.String(length=6), nullable=False),
        sa.Column("longitude", sa.Numeric(precision=10, scale=7), nullable=False),
        sa.Column("latitude", sa.Numeric(precision=10, scale=7), nullable=False),
        sa.Column("station_type", sa.String(length=40), nullable=True),
        sa.Column("source", sa.String(length=200), nullable=False),
        sa.Column("collected_at", sa.DateTime(), nullable=False),
        sa.Column("public_charger_count", sa.Integer(), nullable=True),
        sa.Column("data_source_id", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "latitude BETWEEN -90 AND 90", name=op.f("ck_charging_stations_latitude_range")
        ),
        sa.CheckConstraint(
            "longitude BETWEEN -180 AND 180", name=op.f("ck_charging_stations_longitude_range")
        ),
        sa.CheckConstraint(
            "public_charger_count IS NULL OR public_charger_count >= 0",
            name=op.f("ck_charging_stations_charger_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["data_source_id"],
            ["data_sources.id"],
            name=op.f("fk_charging_stations_data_source_id_data_sources"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_charging_stations")),
        sa.UniqueConstraint("poi_id", name=op.f("uq_charging_stations_poi_id")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("ix_charging_stations_adcode"), "charging_stations", ["adcode"], unique=False
    )
    op.create_index(op.f("ix_charging_stations_city"), "charging_stations", ["city"], unique=False)
    op.create_index(
        op.f("ix_charging_stations_data_source_id"),
        "charging_stations",
        ["data_source_id"],
        unique=False,
    )
    op.create_index(
        "ix_charging_stations_location",
        "charging_stations",
        ["longitude", "latitude"],
        unique=False,
    )
    op.create_table(
        "statistic_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("region_adcode", sa.String(length=6), nullable=False),
        sa.Column("statistic_date", sa.Date(), nullable=False),
        sa.Column("station_count", sa.Integer(), nullable=False),
        sa.Column("public_charger_count", sa.Integer(), nullable=False),
        sa.Column("dc_charger_count", sa.Integer(), nullable=False),
        sa.Column("ac_charger_count", sa.Integer(), nullable=False),
        sa.Column("data_source_id", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "dc_charger_count + ac_charger_count = public_charger_count",
            name=op.f("ck_statistic_snapshots_charger_split"),
        ),
        sa.CheckConstraint(
            "public_charger_count >= 0 AND dc_charger_count >= 0 AND ac_charger_count >= 0",
            name=op.f("ck_statistic_snapshots_chargers_nonnegative"),
        ),
        sa.CheckConstraint(
            "station_count >= 0", name=op.f("ck_statistic_snapshots_station_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["data_source_id"],
            ["data_sources.id"],
            name=op.f("fk_statistic_snapshots_data_source_id_data_sources"),
        ),
        sa.ForeignKeyConstraint(
            ["region_adcode"],
            ["regions.adcode"],
            name=op.f("fk_statistic_snapshots_region_adcode_regions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_statistic_snapshots")),
        sa.UniqueConstraint(
            "region_adcode", "statistic_date", name=op.f("uq_statistic_snapshots_region_adcode")
        ),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("ix_statistic_snapshots_data_source_id"),
        "statistic_snapshots",
        ["data_source_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_statistic_snapshots_region_adcode"),
        "statistic_snapshots",
        ["region_adcode"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # Dropping tables also drops their indexes. MySQL refuses to drop an index
    # while a foreign key still depends on it, so remove child tables first.
    op.drop_table("statistic_snapshots")
    op.drop_table("charging_stations")
    op.drop_table("regions")
    op.drop_table("data_sources")
