import fs from 'node:fs'
const source = new URL('../src/config/design-tokens.json', import.meta.url)
const target = new URL('../src/styles/tokens.css', import.meta.url)
const tokens = JSON.parse(fs.readFileSync(source, 'utf8'))
const css = `/* Generated by scripts/design-tokens.mjs; edit src/config/design-tokens.json. */\n:root {\n${Object.entries(
  tokens,
)
  .map(
    ([layer, values]) =>
      `  /* ${layer} */\n${Object.entries(values)
        .map(([key, value]) => `  --${key}: ${value};`)
        .join('\n')}`,
  )
  .join('\n')}\n}\n`
if (process.argv.includes('--check')) {
  if (fs.readFileSync(target, 'utf8').replaceAll('\r\n', '\n') !== css) {
    console.error('Design tokens are stale; run npm run tokens.')
    process.exitCode = 1
  }
} else fs.writeFileSync(target, css)
